[package]
name = "neural-network"
version = "0.1.0"
edition = "2021"

[dependencies]
mnist = "0.6"
ndarray = "0.16.1"

serde = { version = "1.0", features = ["derive"] }
serde-big-array = { version = "0.3", features = ["const-generics"] }
bincode = "1.3"
flate2 = "1.0"
